#lang datalog

likes(amy, susan).
likes(susan, amy).
likes(amy, mark).
likes(lola, mark).
likes(brewster, mark).
likes(brewster, lucky).
likes(amy, tyrion).
likes(tyrion, amy).
likes(susan, tyrion).
likes(tyrion, susan).

% likes(A, B) :- likes(A, B), B = A.

mutual(A, B) :-
    likes(A, B), likes(B, A).

popular(A) :-
    likes(B, A),
    likes(C, A),
    likes(D, A),
    B != C,
    C != D,
    B != D.

%mutual(A, B)?
%popular(X)?
likes(A, B)?
